# Generated by Django 6.0.6 on 2026-06-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('genre', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(default=8.0)),
                ('episodes', models.IntegerField(default=12)),
                ('trailer_url', models.URLField(blank=True)),
                ('is_trending', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
