# Generated by Django 6.0.6 on 2026-06-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Show in Popular section'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anime',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='Show in Trending section'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.FloatField(default=7.5),
        ),
        migrations.AlterField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
