# Generated by Django 6.0.6 on 2026-06-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anime_is_popular_alter_anime_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='banner',
        ),
        migrations.AddField(
            model_name='anime',
            name='content_type',
            field=models.CharField(choices=[('series', 'Series'), ('movie', 'Movie')], default='series', max_length=10),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
